# Generated by Django 3.2.2 on 2022-05-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobs_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.CharField(max_length=10),
        ),
    ]
