# Generated by Django 3.2.2 on 2022-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobs_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
