# Generated by Django 3.2.2 on 2022-06-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobs_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_category',
            field=models.CharField(default='IT', max_length=50),
        ),
    ]
