# Generated by Django 3.2.2 on 2022-05-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyprofile_specialities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='founded_at',
        ),
    ]
