# Generated by Django 3.2.2 on 2022-05-16 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_companyprofile_founded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='founded_at',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
